Don't rename the METS file when we send the package to AIP storage
This turns out to fail in a non-obvious way: it gets to the storage
fine, but when you withdraw it, Archivematica is unable to retrieve it:

    Traceback (most recent call last):
    File "/src/MCPClient/lib/clientScripts/parse_external_mets.py", line 20, in parse_reingest_mets
      root = etree.parse(mets_path)
    File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
    File "src/lxml/parser.pxi", line 1805, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124318)
    TypeError: cannot parse from 'NoneType'